Fix the following bug caused by a ragged array.
```
Traceback (most recent call last):
  File "<psocake_path>/PeakFindingPanel.py", line 323, in change
    self.paramUpdate(path, change, data)
  File "<psocake_path>/PeakFindingPanel.py", line 336, in paramUpdate
    self.updateClassification()
  File "<psocake_path>/PeakFindingPanel.py", line 555, in updateClassification
    self.drawPeaks()
  File "<psocake_path>/PeakFindingPanel.py", line 830, in drawPeaks
    cenX, cenY = self.assemblePeakPos(peaks)
  File "<psocake_path>/PeakFindingPanel.py", line 780, in assemblePeakPos
    cenX = self.iX[np.array(peaks[:, 0], dtype=np.int64), np.array(peaks[:, 1], dtype=np.int64), np.array(
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
<psocake_path>/PeakFindingPanel.py:826: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```